<script lang="ts">
  import * as Card from "$ui/card";
  import { Button } from "$ui/button";
  import {
    Image as ImageIcon,
    Download,
    QrCode,
    ShieldCheck,
    Share2,
    StickyNote
  } from "@lucide/svelte";
  import { Spinner } from "$ui/spinner";
  import { brandingState } from "$state/branding.svelte";
  import { translatePeriod } from "$utils/translators";

  interface Props {
    clearanceData: {
      name: string;
      stno: string;
      period: string;
      dateIssued: string;
      refNo: string;
      branding: string;
      signatory: string;
      signatoryTitle: string;
    };
    qrDataUrl: string;
    isExporting: boolean;
    onDownloadPDF: () => void;
    onDownloadImage: () => void;
    onShareLink: () => void;
    onShareQR: () => void;
  }

  let {
    clearanceData,
    qrDataUrl,
    isExporting,
    onDownloadPDF,
    onDownloadImage,
    onShareLink,
    onShareQR
  }: Props = $props();

  const activeBranding = $derived(brandingState.profile);

  let clickedAction = $state<string | null>(null);

  $effect(() => {
    if (!isExporting) {
      clickedAction = null;
    }
  });

  function handleAction(type: string, callback: () => void) {
    clickedAction = type;
    callback();
  }

  const clearanceDetails = $derived([
    { label: "Full Name", value: clearanceData.name },
    { label: "Student Number", value: clearanceData.stno, mono: true },
    { label: "Academic Period", value: translatePeriod(clearanceData.period) },
    { label: "Reference Number", value: clearanceData.refNo, mono: true },
    { label: "Date Issued", value: clearanceData.dateIssued }
  ]);
</script>

<div class="w-full max-w-2xl space-y-6 print:hidden">
  <!-- WEB VIEW -->
  <Card.Root class="overflow-hidden shadow-none ring-0 sm:shadow-lg sm:ring-1">
    <Card.Header>
      <div class="flex items-center justify-center">
        <img
          src={activeBranding.logoUrl}
          alt={activeBranding.logoAlt}
          class="h-14 w-auto object-contain transition-all dark:hidden"
        />
        <img
          src={activeBranding.logoUrlDark}
          alt={activeBranding.logoAlt}
          class="hidden h-14 w-auto object-contain transition-all dark:block"
        />
      </div>
    </Card.Header>

    <Card.Content class="space-y-6">
      <section class="space-y-4">
        <div class="mb-2 flex items-center gap-2 border-b pb-2 text-primary">
          <ShieldCheck class="h-4 w-4" />
          <h3 class="text-xs font-semibold tracking-widest uppercase">
            Certificate of Full Payment
          </h3>
        </div>

        <div class="space-y-3 px-1">
          {#each clearanceDetails as detail}
            <div class="flex flex-col gap-0.5 sm:flex-row sm:justify-between">
              <span class="text-xs font-bold text-muted-foreground uppercase">{detail.label}</span>
              <span class="text-sm {detail.mono ? 'font-mono' : 'font-medium'}">{detail.value}</span
              >
            </div>
          {/each}
        </div>
      </section>

      <section class="space-y-2">
        <div class="flex items-center gap-2 border-b pb-2 text-muted-foreground">
          <StickyNote class="h-3 w-3" />
          <h3 class="text-xs font-semibold tracking-widest uppercase">Certification Statement</h3>
        </div>
        <div class="space-y-4 px-1">
          <p class="text-sm leading-relaxed text-muted-foreground">
            This certifies that <span class="font-bold text-foreground">{clearanceData.name}</span>
            has been cleared of any liability regarding association and water fees for the
            <span class="font-bold text-foreground">{translatePeriod(clearanceData.period)}</span>.
          </p>

          <div class="pt-2">
            <div class="flex flex-col items-center border-t border-dashed pt-4">
              <span class="text-xs font-bold uppercase">{clearanceData.signatory}</span>
              <span class="text-xs font-medium text-muted-foreground uppercase"
                >{clearanceData.signatoryTitle}</span
              >
            </div>
          </div>
        </div>
      </section>
    </Card.Content>

    <Card.Footer class="flex flex-col items-center gap-2 border-t bg-muted/10 pt-8 text-center">
      <div class="flex flex-col items-center gap-2">
        <span class="text-xs font-bold tracking-widest text-muted-foreground uppercase"
          >Generated by</span
        >
        <img src="/ha1.svg" alt="HA1 Logo" class="h-10 w-auto opacity-50 contrast-125 grayscale" />
      </div>
      <p class="mt-4 max-w-[350px] text-xs leading-relaxed text-muted-foreground">
        This document is electronically generated and does not require a signature.
      </p>
      {#if qrDataUrl}
        <div class="mt-4 rounded border bg-white p-1 shadow-sm">
          <img src={qrDataUrl} alt="Verification QR" class="h-16 w-16" />
        </div>
      {/if}
    </Card.Footer>
  </Card.Root>

  <div class="mb-2 flex flex-wrap gap-2 px-1">
    <Button
      onclick={() => handleAction("pdf", onDownloadPDF)}
      size="sm"
      variant="secondary"
      disabled={isExporting}
    >
      {#if isExporting && clickedAction === "pdf"}
        <Spinner class="mr-2 h-3.5 w-3.5" />
      {:else}
        <Download class="mr-2 h-3.5 w-3.5" />
      {/if}
      Export PDF
    </Button>
    <Button
      onclick={() => handleAction("image", onDownloadImage)}
      size="sm"
      variant="secondary"
      disabled={isExporting}
    >
      {#if isExporting && clickedAction === "image"}
        <Spinner class="mr-2 h-3.5 w-3.5" />
      {:else}
        <ImageIcon class="mr-2 h-3.5 w-3.5" />
      {/if}
      Save Image
    </Button>
    <Button
      onclick={() => handleAction("qr", onShareQR)}
      size="sm"
      variant="secondary"
      disabled={isExporting}
    >
      {#if isExporting && clickedAction === "qr"}
        <Spinner class="mr-2 h-3.5 w-3.5" />
      {:else}
        <QrCode class="mr-2 h-3.5 w-3.5" />
      {/if}
      Share QR
    </Button>
    <Button
      onclick={() => handleAction("link", onShareLink)}
      size="sm"
      variant="secondary"
      disabled={isExporting}
    >
      {#if isExporting && clickedAction === "link"}
        <Spinner class="mr-2 h-3.5 w-3.5" />
      {:else}
        <Share2 class="mr-2 h-3.5 w-3.5" />
      {/if}
      Share Link
    </Button>
  </div>
</div>
